# Generated by Django 6.0.2 on 2026-02-22 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='آیدی تلگرام')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='یوزرنیم')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام خانوادگی')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره موبایل')),
                ('language_code', models.CharField(default='fa', max_length=10, verbose_name='کد زبان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ عضویت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegram', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'کاربر تلگرام',
                'verbose_name_plural': 'کاربران تلگرام',
            },
        ),
        migrations.CreateModel(
            name='UserState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_state', models.CharField(default='main_menu', max_length=50, verbose_name='وضعیت فعلی')),
                ('temp_data', models.JSONField(blank=True, default=dict, verbose_name='داده\u200cهای موقت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='bot.telegramuser')),
            ],
            options={
                'verbose_name': 'وضعیت کاربر',
                'verbose_name_plural': 'وضعیت کاربران',
            },
        ),
    ]
